In [66]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('fast')

from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import neighbors
from sklearn.metrics import jaccard_similarity_score
from sklearn.metrics import log_loss
from sklearn.metrics import roc_curve, roc_auc_score
import statsmodels.api as sm
import os

## Logistic Regression: This is DataFrame with TMC Dummies

In [2]:
df = pd.read_csv('data/ca_nd.csv')

In [3]:
df.drop('Unnamed: 0',1,inplace=True)

In [4]:
y = df.pop('Severity')

In [5]:
X = np.asarray(df)

In [6]:
X[0:1]

array([[ 0. ,  1. , 75. , 48. , 10. ,  5.8,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ,  1. ,  1. ,  1. ,
         1. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ]])

In [7]:
y = np.asarray(y)

In [8]:
y.shape

(645967,)

In [9]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:1]

array([[-1.91764421e-01,  3.41171862e-01,  7.47302176e-01,
        -4.85245964e-01,  3.72195640e-01, -2.36941695e-01,
        -8.05771484e-02, -1.28110109e-02, -1.69826000e-01,
        -2.64029477e-02, -3.92678970e-01, -1.96371396e-02,
        -1.03542625e-01, -5.27882345e-03, -1.40237946e-01,
        -1.28293801e-01, -1.55420957e-02, -2.85840328e-01,
         6.84624709e-01,  6.19105925e-01,  5.41965964e-01,
         4.78033021e-01, -8.75331635e-01, -6.70044400e-03,
         1.25131305e+00, -1.99757572e-01, -1.41876418e-02,
        -1.77300967e-02, -4.33542467e-01, -4.36244509e-02,
        -7.97163168e-02, -3.51918839e-03, -1.86179968e-01,
        -6.22118681e-03, -7.03850754e-03, -5.87244392e-02,
        -7.67007140e-03, -7.14764373e-03, -5.96714352e-03,
        -5.70179424e-03, -2.25737342e-02, -5.70179424e-03,
        -1.75958603e-03, -1.79906012e-01, -1.39120735e-02,
        -4.12662376e-03, -6.70044400e-03, -6.09548859e-03,
        -1.99502253e-02, -3.04770183e-03, -9.55742006e-0

## Train-Test-Split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=4)
print('Train set: ', X_train.shape, y_train.shape)
print('Test set: ', X_test.shape, y_test.shape)

Train set:  (452176, 95) (452176,)
Test set:  (193791, 95) (193791,)


In [21]:
model = LogisticRegression(C=0.01, multi_class='auto', solver='saga')
model.fit(X_train, y_train)
os.system("say 'modeling has ended. you may continue working'")

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


0

In [22]:
yhat = model.predict(X_test)
yhat

array([2, 2, 2, ..., 2, 2, 2])

In [23]:
yhat_prob = model.predict_proba(X_test)
yhat_prob

array([[0.00417032, 0.65973798, 0.32978067, 0.00631103],
       [0.004585  , 0.63736428, 0.34687243, 0.01117828],
       [0.0043226 , 0.60492718, 0.38314816, 0.00760206],
       ...,
       [0.00361571, 0.96826687, 0.01996713, 0.0081503 ],
       [0.00418273, 0.70366964, 0.28676785, 0.00537978],
       [0.00428176, 0.57730291, 0.41146608, 0.00694925]])

In [24]:
jaccard_similarity_score(y_test, yhat)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.6882466161999268

In [25]:
yhat[0:50]

array([2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2])

In [26]:
y_test[0:50]

array([3, 3, 3, 2, 2, 3, 2, 2, 3, 2, 3, 2, 2, 3, 3, 3, 3, 2, 2, 3, 2, 4,
       2, 2, 3, 3, 3, 3, 3, 2, 3, 3, 3, 2, 3, 2, 2, 2, 2, 3, 2, 3, 3, 2,
       2, 2, 3, 2, 2, 2])

## Logistic Regression: ZERO Dummies Trial

In [30]:
# Log odds: the rati of the probability of the positive to the negative case

def logistic(x):
    return 1/(1 + np.exp(-x))

In [32]:
# Log odds: Sample application
# x = np.arange(-10, 11)
# df = pd.DataFrame(['{:.3f}%'.format(a*100) for a in logistic(x)], index=x, columns=['probability'])
# df.index.name = 'log odds ratio'
# df

In [33]:
# Log loss - used to evaluate the probability outputs (predict_proba) of a classifier 
# instead of its discrete predictions
# ! It favors more strongly the models taht distinguish more strongly the classes.
# !! A low log_loss means low uncertainty/entropy of your model - closer to zero.
# from sklearn.metrics import log_loss
# >>> from sklearn.metrics import log_loss
# >>> y_true = [0, 0, 1, 1]
# >>> y_pred = [[.9, .1], [.8, .2], [.3, .7], [.01, .99]]
# >>> log_loss(y_true, y_pred)
# 0.1738...

In [34]:
new_df = pd.read_csv('data/ca_no_d.csv')

In [36]:
new_df.drop('Unnamed: 0',1,inplace=True)

In [37]:
new_df.head()

Severity  Distance  Side  Temperature  Humidity_pct  Visibility_mi  \
0         3       0.0     1         75.0          48.0           10.0   
1         3       0.0     1         75.0          48.0           10.0   
2         2       0.0     1         82.9          31.0           10.0   
3         3       0.0     1         75.9          48.0           10.0   
4         2       0.0     1         75.2          41.0           10.0   

   Windspeed_mph  Amenity  Bump  Crossing  ...  Showers in the Vicinity  \
0            5.8        0     0         0  ...                        0   
1            4.6        0     0         0  ...                        0   
2            4.6        0     0         0  ...                        0   
3            4.6        0     0         0  ...                        0   
4            5.8        0     0         0  ...                        0   

   Smoke  Snow  T-Storm  Thunder  Thunder in the Vicinity  Thunderstorm  \
0      0     0        0        0                        0             0   
1      0     0        0        0                        0             0   
2      0     0        0        0                        0             0   
3      0     0        0        0                        0             0   
4      0     0        0        0                        0             0   

   Thunderstorms and Rain  Widespread Dust  Wintry Mix  
0                       0                0           0  
1                       0                0           0  
2                       0                0           0  
3                       0                0           0  
4                       0                0           0  

[5 rows x 75 columns]

In [38]:
y = new_df.pop('Severity')

In [41]:
y = np.asarray(y)

In [39]:
X = np.asarray(new_df)

In [42]:
y

array([3, 3, 2, ..., 2, 2, 2])

In [43]:
X

array([[ 0.   ,  1.   , 75.   , ...,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  1.   , 75.   , ...,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  1.   , 82.9  , ...,  0.   ,  0.   ,  0.   ],
       ...,
       [ 0.561,  1.   , 73.   , ...,  0.   ,  0.   ,  0.   ],
       [ 0.772,  1.   , 71.   , ...,  0.   ,  0.   ,  0.   ],
       [ 0.537,  1.   , 79.   , ...,  0.   ,  0.   ,  0.   ]])

## Normalize using <code>StandardScaler()</code>

In [44]:
X = preprocessing.StandardScaler().fit(X).transform(X)
os.system("say 'you may continue working'")
X

array([[-0.19176442,  0.34117186,  0.74730218, ..., -0.00947607,
        -0.00777034, -0.0032919 ],
       [-0.19176442,  0.34117186,  0.74730218, ..., -0.00947607,
        -0.00777034, -0.0032919 ],
       [-0.19176442,  0.34117186,  1.38118817, ..., -0.00947607,
        -0.00777034, -0.0032919 ],
       ...,
       [ 0.67642846,  0.34117186,  0.58682471, ..., -0.00947607,
        -0.00777034, -0.0032919 ],
       [ 1.00296803,  0.34117186,  0.42634725, ..., -0.00947607,
        -0.00777034, -0.0032919 ],
       [ 0.63928652,  0.34117186,  1.06825711, ..., -0.00947607,
        -0.00777034, -0.0032919 ]])

## Train, Test, Split

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=4)

In [46]:
print('Train set: ', X_train.shape, y_train.shape)
print('Test set: ', X_test.shape, y_test.shape)

Train set:  (452176, 74) (452176,)
Test set:  (193791, 74) (193791,)


## Fit the model

In [47]:
model_nd = LogisticRegression(C=0.01, multi_class='auto', solver='saga')
model_nd.fit(X_train, y_train)
os.system("say 'you may continue working'")

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


0

## Prediction and Evaluation

In [48]:
yhat = model_nd.predict(X_test)
yhat

array([2, 2, 2, ..., 2, 2, 2])

In [49]:
yhat_prob = model_nd.predict_proba(X_test)
yhat_prob

array([[0.00227683, 0.62929286, 0.36400211, 0.00442819],
       [0.00251625, 0.62145202, 0.366366  , 0.00966572],
       [0.00235443, 0.57269571, 0.41944725, 0.00550261],
       ...,
       [0.00214226, 0.968119  , 0.02278492, 0.00695382],
       [0.00232157, 0.67429724, 0.31967514, 0.00370604],
       [0.00232489, 0.54249894, 0.45021883, 0.00495733]])

In [50]:
jaccard_similarity_score(y_test, yhat)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.6776940105577658

### The closer to 0 the better

In [53]:
loss_nd = log_loss(y_test, yhat_prob)
loss_nd

0.6260804135044687

In [58]:
# fpr, tpr, thresholds = roc_curve(y_test, yhat_prob)
# Applies only to binary classification

In [64]:
roc_score = roc_auc_score(y_test, yhat_prob, multi_class='ovr')

TypeError: roc_auc_score() got an unexpected keyword argument 'multi_class'

In [65]:
roc_score = roc_auc_score(y_test, yhat_prob)

ValueError: multiclass format is not supported